#!/bin/bash

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -efu -o pipefail

root="$(bazel info workspace)"
cd "${root:?}" || exit

log="$(mktemp)" || exit
trap 'rm -f -- "${log}"' EXIT

bazel coverage -- //... > "${log:?}" || exit
echo

mapfile -t dat < <(sed -r -n -e 's|^  (/.+/coverage\.dat)$|\1|p' -- "${log:?}")

if ((${#dat[@]} == 0)); then
  echo 'No coverage output found' >&2
  exit 1
fi

genhtml --output-directory=coverage-report --branch-coverage \
  -- "${dat[@]}" || exit

echo "Coverage report written to ${root}/coverage-report" >&2
