#!/bin/bash

# Copyright 2021, 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run this script to regenerate the Bazel output and coverage file in
# coverage.org.

set -eu

# Bazel formats output differently when invoked from Emacs.
export INSIDE_EMACS='28.1,compile'

workspace="$(bazel info workspace)" || exit
testdata="${workspace:?}/testdata"
org="${testdata:?}/coverage.org"

dir="$(mktemp -d)" || exit
trap 'rm -r -f -- "${dir}"' EXIT

# Canonicalize the directory so that the textual replacement below doesn’t
# choke on symbolic links.
dir="$(realpath -e -- "${dir:?}")" || exit

# Set up a basic workspace layout in the temporary directory.
emacs --quick --batch --visit="${org:?}" \
  --eval="(let ((default-directory \"${dir:?}/\")) (org-babel-tangle))" || exit

# Remove tangled “bazel-out” directory containing the previous coverage data.
# This would interfere with the Bazel run below.
rm -r -- "${dir:?}/bazel-out"

execroot="$(cd "${dir:?}" && bazel --bazelrc=/dev/null info execution_root)"
testlogs="$(cd "${dir:?}" && bazel --bazelrc=/dev/null info bazel-testlogs)"

# We explicitly compile with the current directory set to a subdirectory to
# ensure that workspace-relative filenames still work as expected.
out="$(cd "${dir:?}/src" && bazel --bazelrc=/dev/null coverage //... 2>&1)"

# Parse output to find location of coverage.dat.  The output should be
# relatively stable, cf. https://bazel.build/run/scripts#parsing-output.
pattern=$'\n''  (/.+/coverage\.dat)'$'\n'
[[ "${out:?}" =~ ${pattern:?} ]] || exit
dat="${BASH_REMATCH[1]}"

# Replace test log directory in the output with a fixed value.  This gets rid
# of the arbitrary build configuration directory.  This needs to happen before
# replacing the execution root because the test log directory is a subdirectory
# of the execution root.
out="${out//${testlogs}/%ROOTDIR%/bazel-out/k8-fastbuild/testlogs}"

# Replace the execution root in the output with a placeholder.
out="${out//${execroot}/%ROOTDIR%}"

# We can’t use ‘org-babel-detangle’ because there are no links in the tangled
# files.
awk -v out=bazel.out -v src=<(echo "${out:?}") \
  -f "${testdata:?}/detangle.awk" \
  -- "${org:?}" > "${dir:?}/org.tmp" || exit

awk -v out=bazel-out/k8-fastbuild/testlogs/src/test/java/example/example_test/coverage.dat \
  -v src="${dat:?}" \
  -f "${testdata:?}/detangle.awk" \
  -- "${dir:?}/org.tmp" > "${org:?}" || exit

echo 'Successfully refreshed coverage.org.'
