#!/bin/bash

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run this script to regenerate the Bazel output and coverage file in
# coverage.org.

set -eu

# Bazel formats output differently when invoked from Emacs.
export INSIDE_EMACS='27.2,compile'

workspace="$(bazel info workspace)" || exit
testdata="${workspace:?}/testdata"
org="${testdata:?}/coverage.org"

dir="$(mktemp --directory)" || exit
trap 'rm --recursive --force -- "${dir}"' EXIT

# Set up a basic workspace layout in the temporary directory.
emacs --quick --batch --visit="${org:?}" \
  --eval="(let ((default-directory \"${dir:?}/\")) (org-babel-tangle))" || exit

execroot="$(cd "${dir:?}" && bazel --bazelrc=/dev/null info execution_root)"

# We explicitly compile with the current directory set to a subdirectory to
# ensure that workspace-relative filenames still work as expected.
out="$(cd "${dir:?}/package" && bazel --bazelrc=/dev/null coverage //... 2>&1)"

# Parse output to find location of coverage.dat.  The output should be
# relatively stable,
# cf. https://docs.bazel.build/versions/4.0.0/guide.html#parsing-output.
pattern=$'\n''  (/.+/coverage\.dat)'$'\n'
[[ "${out:?}" =~ ${pattern:?} ]] || exit
dat="${BASH_REMATCH[1]}"

# Replace the execution root in the output with a placeholder.
out="${out//${execroot}/%ROOTDIR%}"

# We can’t use ‘org-babel-detangle’ because there are no links in the tangled
# files.
awk --lint=fatal \
  --assign out=bazel.out --assign src=<(echo "${out:?}") \
  --file "${testdata:?}/detangle.awk" \
  -- "${org:?}" > "${dir:?}/org.tmp" || exit

awk --lint=fatal \
  --assign out=bazel-out/k8-fastbuild/testlogs/package/library_test/coverage.dat \
  --assign src="${dat:?}" \
  --file "${testdata:?}/detangle.awk" \
  -- "${dir:?}/org.tmp" > "${org:?}" || exit

echo 'Successfully refreshed coverage.org.'
